In [20]:
import pandas as pd
import numpy as np

mid_day = pd.read_csv('dealer_calling_midday.csv')
mid_day2 = mid_day.loc[:,['client','state','active_callers','call_date','contacts_made']]
mid_day2["contacts/caller"] = mid_day2['contacts_made']//mid_day2['active_callers']

checkDates = ['23/01/22','24/01/22','25/01/22','26/01/22','27/01/22','28/01/22','29/01/22']
mid_day2 = mid_day2.loc[(mid_day2["state"]=="Jharkhand") & (mid_day2["call_date"].isin(checkDates))]

contactsAgg = {}
type(mid_day2)
for ind in mid_day2.index:
    if mid_day2['client'][ind] in contactsAgg:
        contactsAgg[mid_day2['client'][ind]] = contactsAgg[mid_day2['client'][ind]] + mid_day2['contacts/caller'][ind]
    else:
        contactsAgg[mid_day2['client'][ind]] = mid_day2['contacts/caller'][ind]

tempDict = {
    'Client': [], 
    'Total Contact(last week)' : [] 
}

for keys in contactsAgg:
    tempDict['Client'].append(keys)
    tempDict['Total Contact(last week)'].append(contactsAgg[keys])

contactsAggDF = pd.DataFrame(tempDict)

contactsAggDF.sort_values(["Total Contact(last week)"], axis=0, ascending=[False], inplace=True)
contactsAggDF


# Import seaborn library
import seaborn as sns
 
# Declaring the cm variable by the
# color palette from seaborn
cm = sns.light_palette("green", as_cmap=True)
 
# Visualizing the DataFrame with set precision
print("\nModified Stlying DataFrame:")
contactsAggDF.style.background_gradient(cmap=cm).set_precision(2)

Modified Stlying DataFrame:

/var/folders/t_/c89s3x9d5pgc71vf3vvks3180000gn/T/ipykernel_1161/3776353132.py:43: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  contactsAggDF.style.background_gradient(cmap=cm).set_precision(2)